# Generated by Django 3.2.8 on 2021-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='about_card_description',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='about_card_heading',
        ),
        migrations.AddField(
            model_name='partners',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_card_icon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
