# Generated by Django 3.2.8 on 2021-10-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20211021_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('button_lebel', models.CharField(max_length=20)),
                ('button_link', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('button', models.CharField(max_length=200)),
            ],
        ),
    ]
