# Generated by Django 3.2.8 on 2021-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_card_icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
